#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

#THEME='catppuccin-mocha-teal-standard+default'
THEME='Breeze-Dark'
ICONS='Papirus'
FONT='Noto Sans 9'
CURSOR='catppuccin-mocha-dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
  ${SCHEMA} gtk-theme "$THEME"
  ${SCHEMA} icon-theme "$ICONS"
  ${SCHEMA} cursor-theme "$CURSOR"
  ${SCHEMA} font-name "$FONT"
  hyprctl setcursor catppuccin-mocha-dark 24
}

apply_themes
