#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## launch wofi with alt config

CONFIG="$HOME/.config/hypr/rofi/config.rasi"

if [[ ! $(pidof rofi) ]]; then
  rofi -show drun -p 'Search...' -config ${CONFIG} -show-icons
else
  pkill rofi
fi
