#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar swaync mpd polkit-kde-auth)
for _prs in "${_ps[@]}"; do
  if [[ $(pidof "${_prs}") ]]; then
    killall -9 "${_prs}"
  fi
done

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (swaync)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start mpd
exec mpd &
nm-applet &
blueman-applet &
