#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## launch waybar with alt config

CONFIG="$HOME/.config/hypr/waybar/config"
DARK_MODE="$HOME/.config/hypr/waybar/mocha.css"
LIGHT_MODE="$HOME/.config/hypr/waybar/latte.css"
STYLE=$DARK_MODE

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
